import Head from 'next/head'
import styles from '@/styles/About.module.css'
import data from '../data/staff.json'
import { useState } from 'react'
import Card from '@/components/Card/about.js'
import Link from 'next/link'

export default function About() {
    console.log(data);
    const [information, setInformation] = useState([...data])

    return(
        <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>Tokidoki Institute of Technology</h1>
        <Link className={styles.link} href="/">Home</Link>
        <div className = {styles.staffContainer}>
          {
            information && information.map((info, index) => {
              if(info.company.toLowerCase() === "tokidoki") {
                return(
                  <Card key={index} name={info.name} department={info.department} position={info.position}/>
                )
              }
            })
          }
        </div>
      </main>
    </>


    )
}